[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pydantic-settings>=2.7.1",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
    "urllib3>=2.3.0",
]
